# Generated by Django 5.0.1 on 2024-06-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutus_category_post_slug_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
