# Generated by Django 5.0.1 on 2024-06-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
