# Generated by Django 5.0.6 on 2024-06-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_image_alter_post_img_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
